### ISSUE TITLE
master_function.py division by 0

### ISSUE THREAD

**Issue by Champuru-san** [sofienkaabar/deep-learning-for-finance#3]
Hey,

I’m testing the functions from your book and encountered an issue.

In "master_function.py" (lines 175–177), there’s a division by zero. However, the book doesn’t seem to explain why dividing by zero is necessary.

When I execute "2_Linear_Regression.py", I get the following error:
RuntimeWarning: invalid value encountered in divide
plotting_time_series[0:first, 1] = plotting_time_series[0:first, 1] / 0

This warning is triggered for every line between 175 and 177.

Could you clarify what value should be used there instead of zero?

**Comment by sofienkaabar** [comment]
Hi Champuru-san,
Thank you for your feedback. Indeed, while the code works despite the runtime error, the fact that we're dividing by zero was a lazy shortcut to achieve values that start from a different index. 

Dividing certain values by zero will result in Nan, a non-value that cannot be plotted, and thus ignored. By calibrating them such as is done in the function, we can get the desired result which is to align test values that begin just after the end of train values and in parallel to the forecasted values.

Nevertheless, I do agree that this is not the ideal way to handle such an issue (data frames and python could have been another solution), but it achieves the same results.

You can ignore this error by typing:
**import warnings
warnings.filterwarnings("ignore")**

However, that would remove other warnings.
Hope this helps,

Best,
Sofien

**Comment by Champuru-san** [comment]
Thank you for your feedback.

So the goal was to achieve NaN? Then couldn't we write the code as:
    plotting_time_series[0:first, 1] = np.nan
    plotting_time_series[0:first, 2] = np.nan
    plotting_time_series[first:, 0] = np.nan
?

**Comment by sofienkaabar** [comment]
Absolutely! Thank you. Amended it!
